### ISSUE TITLE
make server chain elements to do its work on return side of its next.Request

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-ovs#25]
## Expected Behavior

As per feedback given [here](https://github.com/networkservicemesh/sdk-ovs/pull/23#issuecomment-923047814), make all of `sdk-ovs` and its dependent relevant `sdk-sriov `and `sdk-kernel `server chain elements to follow this guideline: `add information/make decisions' on the call side of the Request and 'do work' on the return side`

## Current Behavior

Currently most of the server chain elements follows the below pattern for doing its work: `do_its_work -> return_if_work_fails -> next.Request -> cleanup_its_work_done_previously_when_next_request_fails -> return`

**Comment by denis-tingaikin** [comment]
It looks like this is done by #23
