### ISSUE TITLE
Remaining bridge interfaces after forwarder stoped

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/sdk-ovs#276]
## Expected Behavior

After forwarder stopped any interface created and no longer used should be deleted 

## Current Behavior

The following interfaces remains in the host after forwarder stopped (graceful termination) even after NSM system removal (kubernetes namespace delete): ovs-system and nsm-br - the main bridge interface used by NSM.

## Failure Information (for bugs)

The NSM's main bridge should be deleted when forwarder-ovs is stopped, but to delete the ovs-system is risky. In the case of host-ovs this might be used by others. When the OVS is running inside forwarder pod in case of pod termination the ovs is stopped forcefully without the chance to delete the system bridge.

## Steps to Reproduce

1. Start the basic NSM system (registry, nsmgr, forwarder-ovs)
2. Delete the namespace
3. Check the host for remainder interfaces (ovs-system, nsm-br)

**Comment by denis-tingaikin** [comment]
@edwarnicke  Don't you mind if we take care of this?


@ljkiraly Would you like to fix this one?

**Comment by ljkiraly** [comment]
@denis-tingaikin During the fix of issue [9778](https://github.com/networkservicemesh/deployments-k8s/issues/9778) I noticed these remaining interfaces. I can take this one.

**Comment by denis-tingaikin** [comment]
@ljkiraly it'd be fantastic!

**Comment by ljkiraly** [comment]
Fix merged and verified.
